### ISSUE TITLE
Build error caused by recent commit

### ISSUE THREAD

**Issue by isolationism** [stldo/gatsby-transformer-yaml-full#14]
I recently upgraded my toolchain and went from `gatsby-transformer-yaml-full` version 0.4.2 ==> 0.4.5 and experienced the following error message immediately upon attempting to start Gatsby:

```
$ gatsby develop

 ERROR 

Error in "/projects/app-client/node_modules/gatsby-transformer-yaml-full/gatsby-node.js": Unexpected token '.'

  Error: /projects/app-client/node_modules/gatsby-transformer-yaml-full/gatsby-node.js:80
      } else if (isPlainObject(content) && !content.internal?.type) {
                                                             ^
  SyntaxError: Unexpected token '.'
```

I suspect there is logical problem here combining the "not" operator with optional chaining that might be remedied by wrapping in parens, i.e. `!(content.internal?.type)`

**Comment by stldo** [comment]
Hi! Optional chaining started to be supported on Node.js 14, you might be using a lower version. I've replaced the optional chaining operator, please update to 0.4.6, it must be working now. If the issue continues, please let me know. Thanks for reporting it!
