### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by usulpro** [stldo/gatsby-transformer-yaml-full#2]
Hey! Thanks for the plugin :+1:  it is really very handy to keep markdown in yaml files

The only thing that is missing is syntax highlighting for markdown. Do you have any ideas how to enable it? I usually use VSCode but I'd happy to have a solution in any online/offline editor

**Comment by stldo** [comment]
Hi! Sorry, I don't have any idea for it. An option could be modifying the default VSCode YAML highlight extension.

**Comment by stldo** [comment]
I've updated the markdown plugin, so you can import external files like in the following: `property: !markdown ./file.md`. I hope this may help you.
