### ISSUE TITLE
gatsby-transformer-yaml-full single document sourcing no longer working properly

### ISSUE THREAD

**Issue by tromika** [stldo/gatsby-transformer-yaml-full#3]
Following the docs https://github.com/stldo/gatsby-transformer-yaml-full/tree/master/packages/gatsby-transformer-yaml-full#single-document I run into an odd behavior.

I've created 2 yaml files within a folder
![image](https://user-images.githubusercontent.com/540472/82814528-a2650080-9e97-11ea-8c77-9a6e62c9060d.png)

Using 0.2.0 I got what's expected
![image](https://user-images.githubusercontent.com/540472/82814819-30d98200-9e98-11ea-9a95-99731bdb85a2.png)

0.3.0 & 0.3.1 only returns only one node (as I experienced usually the last modified file)
![image](https://user-images.githubusercontent.com/540472/82814205-f28f9300-9e96-11ea-9de5-c59dff424be0.png)

Thanks for your help in advance!

**Comment by stldo** [comment]
Hi! I had looked into it and this bug should be fixed on 0.3.2. Thanks for pointing it out!

**Comment by tromika** [comment]
@stldo 🙇‍♂️
