### ISSUE TITLE
Allow plugins to return a list of types

### ISSUE THREAD

**Issue by multimeric** [stldo/gatsby-transformer-yaml-full#4]
I haven't actually run this plugin yet, but from looking at [the code](https://github.com/stldo/gatsby-transformer-yaml-full/blob/1e9d307ba669ec09afa19cabe4d28081a6c3549d/packages/gatsby-transformer-yaml-full/gatsby-node.js#L71-L77), you assume each plugin returns exactly one type, which seems inconvenient. This way, if you have 100 custom types you'd need to create 100 modules, ie 100 `.js` files. My own use-case has about 20, so you can see why I want this.

**Comment by stldo** [comment]
Ok, I'm looking into it and I will update the code soon. I've thought about this possibility but I didn't imagine a use case for it, do you mind sharing yours?

**Comment by multimeric** [comment]
Sure, happy to explain. I have a nested Python data structure that contains about 20 classes, which I have serialized to YAML, using YAML types/tags to indicate the original Python class. *One* use of this YAML file is using it to build a static site using Gatsby, but it has a few other uses that require the classes to be there. I now need to access the contents of this file from Gatsby, but doing so causes js-yaml to throw errors since it's encountering a heap of tags it hasn't seen before. Ideally there would be a flag to just tell js-yaml to just ignore tags, but since there isn't, I'll have to provide a schema that lists all my tags and what kind of JS structure they should be converted to. However I don't want to have to create 20 JS files to do this. Does that help?

**Comment by stldo** [comment]
Thank you very much for your explanation and the pull request. I'll merge it and publish right now.
