### ISSUE TITLE
Custom type plugin qraphql error on save YAML file

### ISSUE THREAD

**Issue by PaulBunker** [stldo/gatsby-transformer-yaml-full#8]
Hi, I'm having some difficulty creating a custom type plugin. 

The goal is to take a youtube videoID fetch the thumbnail url and title using the YouTube API 

The plugin works as expected on first pass, however after editing and saving the yaml file I get an error `Cannot query field "allVideosYaml" on type "Query".` I think it has something to do with gatsby re-rwiting the schema before the construct function has completed. 

Am I approaching this in the right way do you think?

```javascript
// index.js

const YOUTUBE_API_KEY = "abcd"
const fetch = require("node-fetch")

module.exports = () => ({
  tag: "!YouTube",
  options: {
    kind: "scalar",
    construct: async (id) => {
      const response = await fetch(
        `https://www.googleapis.com/youtube/v3/videos?part=snippet&id=${id}&key=${YOUTUBE_API_KEY}`
      )
      const data = await response.json()
      const {
        title,
        thumbnails: {
          medium: { url },
        },
      } = data.items[0].snippet
      return {
        title,
        thumbnail: url,
        id,
      }
    },
  },
})

```
```yaml
// videos.yaml
video: !YouTube 5uG7unM1ewE
content: !markdown |
  #some description text
```

Thanks for taking a quick look if you get a moment.
-Paul

**Comment by stldo** [comment]
Hi! I'm very busy lately, sorry for taking so long to reply. I'm investigating what is going on, could you please share your Gatsby version?

**Comment by PaulBunker** [comment]
Hi stldo, 

No problemo, thanks for the plugin I had a dig through the code and eventually found a solution.

I'm usually right up-to-date with my gatsby version in this project. 

The error message reminded me of similar messages I have had in the past where the solution was to add a dummy markdown file with all yaml fields I might want to use so I tried adding types via `createSchemaCustomization` in `gatsby-node` at the root of my project, this didn't work. After pretty much ripping off your plugin but hardcoding for my requirements in an attempt to understand better what was going on, I was getting the same error.  Adding the types in the local plugin folder finally solved the issue. The solution baffled me somewhat, but at the point I got it working I decided not to touch it again.

I wonder if there might be a way to pass the types into the plugin via options and dynamically create `createSchemaCustomization`? 

I'm happy for you to close this issue since I found a workaround for my problem that I'm happy with.

Thanks again -Paul

**Comment by stldo** [comment]
After some investigation, I think that it could be a Gatsby bug. I filled an issue (https://github.com/gatsbyjs/gatsby/issues/28795) there. Thank you very much for all information provided!

**Comment by msroberts** [comment]
Is there a workaround for this issue?  I'm also running into this issue trying to use createFilePath from gatsby-source-filesystem with yaml source files.

**Comment by PaulBunker** [comment]
What issue are you running into? 

Edit: can you post some code and I can try to help. I have this plugin working including with custom transformers. I had to use createSchemaCustomization in gatsby-node to avoid crashes while editing files. Works like a charm though.

**Comment by msroberts** [comment]
I'm not using createSchemaCustomization, so maybe that would fix my issue.  Is that in a code sample somewhere?

**Comment by PaulBunker** [comment]
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/

**Comment by stldo** [comment]
Hi @msroberts! Could you please share more information about your use case? I'm working on a fix for this issue, your information may be very helpful. Meanwhile, on 0.4.x version, as a workaround you can try saving the file — i.e. `command + S` in VSCode — two consecutive times. The first save will throw an error, while on the second it should work fine. Everything should be working fine on build/production, but if you're getting any errors, please send the error here and I'll check it.

**Comment by msroberts** [comment]
@stldo I'll see if I can create a demo repo.

**Comment by stldo** [comment]
It seems that this issue will not be solved by Gatsby too soon. It affects even the official `gatsby-transformer-yaml` plugin — it throws an error if a field containing a path to a file is changed to another file path (the double saving trick can make it work: the first time, GraphQL will detect the field value as a string; the second time it'll be detected as a file node). Right now, the only workaround I know for this issue is saving the file two consecutive times. I'll close this issue, it's a bug on the Gatsby side that requires some work to fix it.
